[package]
name = "music3-client"
version = "0.1.0"
edition = "2021"
license = "MIT or Apache-2.0"

[dependencies]
music3-common = { path = "../common" }
reqwest = { version = "0.12.7", default-features = false, features = ["json", "rustls-tls"] }
