[package]
name = "music3-shuttle"
version = "0.1.0"
edition = "2021"
license = "MIT or Apache-2.0"

[dependencies]
music3-server = { path = "../server" }
shuttle-axum = "0.47.0"
shuttle-runtime = "0.47.0"
zeroize = "1.8.1"
